BUGFIX: Process Flow
Error message:
ModuleError: failed to load 'sap/m/nodes.js' from /sap/public/bc/ui5_ui5/resources/sap/m/nodes.js

The "ns = `commons`" was missing in the "NODES" method.